Task2_AspNetCore/Task2_AspNetCore.WebUI/Models/Data/Entities/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Task2_AspNetCore.WebUI.Models.Data.Enumeration;

namespace Task2_AspNetCore.WebUI.Models.Data.Entities
{
    public class Country
    {
        public int CountryId { get; set; }

        public string Name { get; set; }
        public double Population { get; set; }
        public double Size { get; set; }
        public bool IsG20Member { get; set; }
        public Continent Continent { get; set; }
    }
}

Task2_AspNetCore/Task2_AspNetCore.WebUI/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using Task2_AspNetCore.WebUI.Models.Data.Abstraction;
using Task2_AspNetCore.WebUI.Models.Data.Entities;
using Task2_AspNetCore.WebUI.Models.Data.Realization;

namespace Task2_AspNetCore.WebUI.Controllers
{
    public class CountryController : Controller
    {
        private ICountryRepository m_repository;

        public CountryController(CountryRepository repository)
        {
            m_repository = repository;
        }

        public ActionResult GetCountryList()
        {
            return View(m_repository.GetCountrys());
        }

        public ActionResult GetCountryBy(Int32? id)
        {
            if (id == null)
            {
                return this.RedirectToAction(nameof(this.GetCountryList));
            }
            return View(m_repository.GetCountry((Int32)id));
        }

        public ActionResult DeleteCountry(Int32? id)
        {
            if (id != null)
            {
                m_repository.Delete(this.m_repository.GetCountry((Int32)id));
            }
            return this.RedirectToAction(nameof(this.GetCountryList));
        }

        [HttpGet]
        public ActionResult AddNewCountry()
        {
            return View(new Country());
        }

        [HttpPost]
        public ActionResult AddNewCountry(Country country)
        {
            if (country != null)
            {
                m_repository.Add(country);
            }
            return this.RedirectToAction(nameof(this.GetCountryList));
        }

        [HttpGet]
        public ActionResult UpdateCountry(Int32? id)
        {
            if (id == null)
            {
                return this.RedirectToAction(nameof(this.GetCountryList));
            }
            return View(m_repository.GetCountry((Int32)id));
        }

        [HttpPost]
        public ActionResult UpdateCountry(Country country)
        {
            if (country != null)
            {
                m_repository.Update(country);
            }
            return this.RedirectToAction(nameof(this.GetCountryList));
        }

        [HttpGet]
        public ActionResult SearchBy()
        {
            return View(new List<Country>());
        }

        [HttpPost]
        public ActionResult SearchBy(String sortString)
        {
            if (sortString != null)
            {
                // поддерживаемые ключевые слова для поиска (примеры):
                // name:Федер
                // isG20:true
                // isG20:false
                // continent:Eurasia
                List<Country> searchResult = m_repository.SortBy(sortString);
                return View(searchResult);
            }
            return this.RedirectToAction(nameof(this.SearchBy));
        }

        public ActionResult GetStatistics()
        {
            List<KeyValuePair<string, string>> statistic = m_repository.GetStatistic();
            return View(statistic);
        }
    }
}

Task2_AspNetCore/Task2_AspNetCore.WebUI/Views/Country/AddNewCountry.cshtml
@model Task2_AspNetCore.WebUI.Models.Data.Entities.Country

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<body>
    <label><a href="~/Country/GetCountryList">Возврат в основное меню</a></label>
    <h2>Добавить новую страну</h2>
    @using (Html.BeginForm("AddNewCountry", "Country", FormMethod.Post))
    {
        <table>
            <tr>
                <td>Наименование страны:</td>
                <td>@Html.TextBoxFor(country => country.Name, "")</td>
            </tr>

            <tr>
                <td>Численность населения (чел.):</td>
                <td>@Html.TextBoxFor(country => country.Population, "", new { type = "number" })</td>
            </tr>

            <tr>
                <td>Площадь (км^2):</td>
                <td>@Html.TextBoxFor(country => country.Size, "", new { type = "number" })</td>
            </tr>
            <tr>
                <td>Участник G20:</td>
                <td>@Html.CheckBoxFor(country => country.IsG20Member)</td>
            </tr>
            <tr>
                <td>Континент:</td>
                <td>@Html.DropDownListFor(country => country.Continent, Html.GetEnumSelectList(typeof(Task2_AspNetCore.WebUI.Models.Data.Enumeration.Continent)))</td>
            </tr>
        </table>
        <div><input type="submit" class="btn btn-default" value="Отправить" /></div>
    }
</body>
</html>

Task2_AspNetCore/Task2_AspNetCore.WebUI/Views/Country/GetCountryBy.cshtml
@model Task2_AspNetCore.WebUI.Models.Data.Entities.Country

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Детальная информация о стране</title>
</head>
<body>
    <label><a href="~/Country/GetCountryList">Возврат в основное меню</a></label>
    <h3>Страна</h3>
    <table>
        <tr>
            <td>Наименование страны:</td>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <td>Численность населения (чел.):</td>
            <td>@Model.Population</td>
        </tr>
        <tr>
            <td>Площадь (км^2):</td>
            <td>@Model.Size</td>
        </tr>
        <tr>
            <td>Расположение (континент):</td>
            <td>@Model.Continent.ToString()</td>
        </tr>
        <tr>
            <td>Участник G20:</td>
            @if (Model.IsG20Member)
            {
                <td>Да</td>
            }
            else
            {
                <td>Нет</td>
            }
        </tr>
    </table>
</body>
</html>

Task2_AspNetCore/Task2_AspNetCore.WebUI/Views/Country/GetCountryList.cshtml
@model IEnumerable<Task2_AspNetCore.WebUI.Models.Data.Entities.Country>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title>Перечень основных характеристик стран</title>
    </head>
    <body>
        <label><a href="~/Country/GetStatistics">Статистика по странам</a></label>
        <label><a href="~/Country/AddNewCountry">Добавить страну</a></label>
        <label><a href="~/Country/SearchBy">Поиск</a></label>
        <h3>Страны</h3>
        <table>
            <tr>
                <td>Наименование страны:</td>
                <td>Континент:</td>
                <td>Площадь (км^2):</td>
                <td>Действие:</td>
                <td>Действие:</td>
            </tr>
            @foreach (var country in Model)
            {
                <tr>
                    <td><a href="~/Country/GetCountryBy/@country.CountryId">@country.Name</a></td>
                    <td>@country.Continent.ToString()</td>
                    <td>@country.Size.ToString()</td>
                    <td><a href="~/Country/DeleteCountry/@country.CountryId">Удалить</a></td>
                    <td><a href="~/Country/UpdateCountry/@country.CountryId">Редактировать</a></td>
                </tr>
            }
        </table>
    </body>
</html>


Task2_AspNetCore/Task2_AspNetCore.WebUI/Views/Country/GetStatistics.cshtml
@model List<KeyValuePair<String, String>>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Статистика по каталогу стран:</title>
</head>
<body>
    <label><a href="~/Country/GetCountryList">Возврат в основное меню</a></label>
    <h3>Статистика по странам</h3>
    <table>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Key</td>
                <td>@item.Value</td>
            </tr>
        }
    </table>
</body>
</html>

Task2_AspNetCore/Task2_AspNetCore.WebUI/Views/Country/SearchBy.cshtml
@model List<Task2_AspNetCore.WebUI.Models.Data.Entities.Country>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<body>
    <label><a href="~/Country/GetCountryList">Возврат в основное меню</a></label>
    <h2>Поиск страны по имени</h2>
    @using (Html.BeginForm("SearchBy", "Country", FormMethod.Post))
    {
        <table>
            <tr>
                <td>Введите критерий поиска:</td>
                <td><input type="text" name="sortString" /></td>
            </tr>
        </table>
        <div><input type="submit" class="btn btn-default" value="Поиск" /></div>
        <label>
            поддерживаемые ключевые слова для поиска (примеры):<br>
            name:Федер<br>
            isG20:true<br>
            isG20:false<br>
            continent:Eurasia
        </label>
    }

    @if (Model.Count != 0)
    {
        <table>
            <tr>
                <td>Наименование страны:</td>
                <td>Континент:</td>
                <td>Площадь (км^2):</td>
                <td>Действие:</td>
                <td>Действие:</td>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td><a href="~/Country/GetCountryBy/@item.CountryId">@item.Name</a></td>
                    <td>@item.Continent.ToString()</td>
                    <td>@item.Size.ToString()</td>
                    <td><a href="~/Country/DeleteCountry/@item.CountryId">Удалить</a></td>
                    <td><a href="~/Country/UpdateCountry/@item.CountryId">Редактировать</a></td>
                </tr>
            }
        </table>
    }
</body>
</html>

Task2_AspNetCore/Task2_AspNetCore.WebUI/Views/Country/UpdateCountry.cshtml
@model Task2_AspNetCore.WebUI.Models.Data.Entities.Country

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<body>
    <label><a href="~/Country/GetCountryList">Возврат в основное меню</a></label>
    <h2>Обновить параметры страны</h2>
    @using (Html.BeginForm("UpdateCountry", "Country", FormMethod.Post))
    {
        @Html.HiddenFor(country => country.CountryId)
        <table>
            <tr>
                <td>Наименование страны:</td>
                <td>@Html.TextBoxFor(country => country.Name)</td>
            </tr>

            <tr>
                <td>Численность населения (чел.):</td>
                <td>@Html.TextBoxFor(country => country.Population, new { type = "number" })</td>
            </tr>

            <tr>
                <td>Площадь (км^2):</td>
                <td>@Html.TextBoxFor(country => country.Size, new { type = "number" })</td>
            </tr>
            <tr>
                <td>Участник G20:</td>
                <td>@Html.CheckBoxFor(country => country.IsG20Member)</td>
            </tr>
            <tr>
                <td>Континент:</td>
                <td>@Html.DropDownListFor(country => country.Continent, Html.GetEnumSelectList(typeof(Task2_AspNetCore.WebUI.Models.Data.Enumeration.Continent)))</td>
            </tr>
        </table>
        <div>
            <input type="submit" class="btn btn-default" value="Редактировать" />
        </div>
    }
</body>
</html>